#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A relaxing and satisfying marble matching game

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Colwin Fernandes                               
your_link                                 :                      
your_city                                 : Pune
email_address                             : emil.baehr@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : colwinf
github_username                           : colwin
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Multiple Marble Packs
    description                           : Choose between multiple colourful marble packs! 
    fontawesome_icon_name                 : magic
    
  - title                                 : Difficulty Levels
    description                           : Pick your difficulty level to play on. Choose between Easy, Medium and Hard. Each level has its own challenges.
    fontawesome_icon_name                 : hat-wizard

  - title                                 : No In-App Purchases
    description                           : Pay one price and enjoy lifetime updates to the app. We will be adding more marble packs and possibly game modes soon!
    fontawesome_icon_name                 : money-bill-alt

  - title                                 : No Advertising
    description                           : The app is supported by your dollars. So we don't need to add invasive tracking to it to serve you advertising. 
    fontawesome_icon_name                 : ban

  - title                                 : Fun for all ages
    description                           : Popping the marbles is fun for all ages. The secret to getting a 3 star score is to end the game with the smallest marbles you can. 
    fontawesome_icon_name                 : heart

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
